teadb/urls.py
from django.conf.urls import url
from django.contrib import admin

from tea.views import IndexView, TeaDetailView, CreateReviewView, AddTeaView, AddTeaTypeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',IndexView.as_view(), name='index'),
    url(r'^tea/(?P<pk>[0-9]+)/$', TeaDetailView.as_view(), name='tea_detail'),
    url(r'^tea/(?P<pk>[0-9]+)/reviews/create/$', CreateReviewView.as_view(), name='create_review'),
    url(r'^tea/add/$', AddTeaView.as_view(), name='add_tea'),
    url(r'^tea/type/add/$', AddTeaTypeView.as_view(), name='add_tea_type'),
]

tea/models.py
from django.db import models

class TeaType(models.Model):
    tea_type = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % self.tea_type

class Tea(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TeaType)
    description = models.TextField()
    region = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Review(models.Model):
    reviewed_tea = models.ForeignKey(Tea)
    content = models.TextField()
    author = models.CharField(max_length=50)

tea/views.py
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, FormView
from tea.models import Tea, Review, TeaType


class IndexView(ListView):
    template_name = "tea/index.html"
    model = Tea


class TeaDetailView(DetailView):
    template_name = "tea/tea_detail.html"
    model = Tea


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'author']


class CreateReviewView(FormView):
    form_class = ReviewForm
    template_name = 'tea/create_review.html'

    def form_valid(self, form):
        review = form.save(commit=False)
        review.reviewed_tea = Tea.objects.get(id=self.kwargs['pk'])
        review.save()
        return HttpResponseRedirect(reverse('tea_detail', args=(self.kwargs['pk'])))

    def get_context_data(self, **kwargs):
        context = super(CreateReviewView, self).get_context_data(**kwargs)
        context['tea'] = Tea.objects.get(id=self.kwargs['pk'])
        return context


class TeaAddForm(ModelForm):
    class Meta:
        model = Tea
        fields = ['name', 'type', 'description', 'region']


class AddTeaView(FormView):
    form_class = TeaAddForm
    template_name = 'tea/add_tea.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('index'))


class TeaTypeAddForm(ModelForm):
    class Meta:
        model = TeaType
        fields = ['tea_type']


class AddTeaTypeView(FormView):
    form_class = TeaTypeAddForm
    template_name = 'tea/add_tea_type.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('index'))

tea/templates/show_create_review_form.html
 <form method="post" action="{% url 'create_review' tea_id %}">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Zapisz">
 </form>

tea/templates/show_tea_detai.html
<h1>Nazwa: {{ tea.name }}</h1>
<p>Rodzaj: {{ tea.type }}</p>
<p>Opis: {{ tea.description }}</p>
<p>Region: {{ tea.region }}</p>

tea/templates/show_tea_reviews.html
<ul>
{% for review in reviews %}
    <li> {{ review.content }} - {{ review.author }} </li>
{% endfor %}
</ul>

tea/templates/tea/add_tea.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
    <a href="{% url 'index' %}">Powrót</a>
{% endblock %}

tea/templates/tea/add_tea_type.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
    <a href="{% url 'index' %}">Powrót</a>
{% endblock %}

tea/templates/tea/create_review.html
{% extends 'base.html' %}
{% load tea_detail %}

{% block content %}
    {% show_tea_detail tea.id %}

    <p>Recenzje:</p>
    {% show_tea_reviews tea %}

    <p>Dodaj recenzje:</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
{% endblock %}

tea/templates/tea/index.html
{% extends "../templates/base.html" %}

{% block title %} TeaDB index {% endblock %}

{% block content %}
    {% if tea_list %}
    <ul>
    {% for tea in tea_list %}
        <li><a href="{% url 'tea_detail' tea.id %}">{{ tea }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    brak herbat w bazie danych
    {% endif %}
    <p><a href="{% url 'add_tea' %}">Dodaj herbatę</a></p>
    <p><a href="{% url 'add_tea_type' %}">Dodaj typ herbaty</a></p>
{% endblock %}

tea/templates/tea/tea_detail.html
{% extends 'base.html' %}
{% load tea_detail %}

{% block content %}
    <h1>Nazwa: {{ tea.name }}</h1>
    <p>Rodzaj: {{ tea.type }}</p>
    <p>Opis: {{ tea.description }}</p>
    <p>Region: {{ tea.region }}</p>
    <p>Recenzje:</p>
    {% if tea.review_set.count %}
        {% show_tea_reviews tea %}
    {% else %}
        <p>Brak recenzji dla tej herbaty.</p>
    {% endif %}
    <p>Dodaj recenzję</p>
    {% show_create_review_form tea.id %}
    <a href="{% url 'index' %}">Powrót</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tytuł{% endblock %}</title>
</head>

<body>
{% block content %}content{% endblock %}
</body>

</html>